### ISSUE TITLE
Add underlying asset to MarketContract data

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/MARKETProtocol#107]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user I would like to be able to get back the underlying asset data easily from a field on the Market Contract.  

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

For easily accessing the underlying asset data for development/ux/ui purposes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

### Current Behavior
[comment]: # (Describe what actually happened.)
This data is currently missing(only collateral token data is available)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Underlying asset symbol is returned with the market contract data

in cases of assets with no symbol such as wheat, I think we should use the entire word capitalized.

**Comment by pelsasser** [comment]
Closing in favor of contract naming specifications #44
