### ISSUE TITLE
Being primary exploratory integration with ChainLink

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#118]
### User Story
As a user, I would like to be able to use ChainLink and not just oraclize.it

### Why Is this Needed?
*Summary*: ChainLink is awesome

### Description
*Type*: Feature

### Definition of Done
- [ ] understand MVP needed to create a chainlinked implementation
- [ ] research ability to run chainlink node in docker connected to local truffle instance for testing

### Needed clarity
- [ ] Does the sleep functionality pause all requests?  How can we create a callback in the future, but allow for spot requests by end users.
- [ ] How do we abstract the need for Link? Can factory address hold needed Link for deployment.

**Comment by pelsasser** [comment]
Link to sleep adapter - https://github.com/smartcontractkit/chainlink/wiki/Adapters#sleep

**Comment by thodges-gh** [comment]
Hi @pelsasser! I think this covers your clarification points. Feel free to ask for clarification as they come up in the future.

> Does the sleep functionality pause all requests?

It does not. The Chainlink node will manage sleep requests as their own channel, so you can even create multiple sleep requests simultaneously, with different durations, and still receive each callback when you would expect them.

> How can we create a callback in the future, but allow for spot requests by end users.

Multiple request methods, even on separate contracts, can use the same callback method on the same contract, if desired. So you could have one request using a sleep adapter, and a separate request that responds immediately, both sharing the same callback method.

> How do we abstract the need for Link? Can factory address hold needed Link for deployment.

Yes, you could create a factory address to hold LINK, and when requesting contracts are created, some amount of LINK is sent to it. The request payload is sent with the LINK transfer from the requesting contract to the oracle contract, which initiates the request with the oracle service off-chain.

Additionally, we have some contract examples in our documentation, [here](https://docs.chain.link/docs/contract-examples), which should help you with creating requests.

**Comment by pelsasser** [comment]
@thodges-gh - thanks a ton for the response here!

I am planning on working on some implementations this week, I also forked your repo which shows some truffle tests with an oracle deployed contract, so that certainly helps with the needed dev process.

I will keep you guys in the loop, and perhaps next week or two we can go over the MVP together

**Comment by pelsasser** [comment]
@thodges-gh - can you help me understand the `specID` is this just an external ID for our own use for tagging requests?

**Comment by thodges-gh** [comment]
Sure thing! The `specID` is an ID used by the oracle node to know what set of tasks to run for your request. We have documentation [here](https://docs.chain.link/v1.0/docs/job-specifications) that goes into further detail. In the future, we'll have an easy way of translating requirements into a job spec, but until then, if you want to describe to me what the request needs, I can provide the job spec for you and show how to use it.

**Comment by pelsasser** [comment]
Okay, awesome.

I think to start the ideal implementation would be to constrain it to parsing a returned json object from an rest api.

We are doing this with oraclize.it using some parsing helpers, the helpers of course vary by API structure, but allow a user to specify those by passing them into our contract constructor.

For example, by supplying this to oraclize.it 
```
json(https://api.kraken.com/0/public/Ticker?pair=ETHUSD).result.XETHZUSD.c.0
```

The api returns 

> {"error":[],"result":{"XETHZUSD":{"a":["284.97000","1","1.000"],"b":["284.67000","5","5.000"],"c":["285.00000","6.50000000"],"v":["42848.03031479","45508.01617768"],"p":["279.57060","280.09336"],"t":[7211,7892],"l":["270.44000","270.44000"],"h":["291.00000","291.59000"],"o":"288.07000"}}}

Which is parsed by oraclize.it and return to our callback as a string, in this case `285.00000` which we then parse into an integer as in the below code snippet

```
lastPrice = parseInt(result, PRICE_DECIMAL_PLACES);
```

So ideally, a user (with the assistance of our dApp) would be able to pass into a constructor everything needed to create a correct `run` object for ChainLink

Hopefully this makes sense, happy to discuss further on the phone or in our [discord](https://marketprotocol.io/discord)

**Comment by thodges-gh** [comment]
Perfect, this is exactly what I needed to know. Our request and response methods work similar, and you can even place some parameters which should be static in the spec itself so that you don't have to specify it on-chain for each request. However, specifying everything in the request itself does make the process a lot easier to understand. That said, here's a complete (though minimal) working example that could be copy and pasted into Remix pointed to Rinkeby, or if you fix the import line, used in your Truffle tests, and works right now. Pretty much anything in the `requestPrice` method could be set with an input parameter, I just left everything the way it is for clarity.

```solidity
pragma solidity ^0.4.24;

import "github.com/smartcontractkit/chainlink/solidity/contracts/Chainlinked.sol";

contract MarketProtocolConsumer is Chainlinked, Ownable {
  address constant RINKEBY_LINK_ADDRESS = 0x01BE23585060835E02B77ef475b0Cc51aA1e0709;
  address constant RINKEBY_ORACLE_ADDRESS = 0x1b12694E8651389c5BB3C094E8fb7e5609b663E7;
  bytes32 constant SPEC_ID = bytes32("b4eaae96efc041d78458960456872047");
  uint256 public price;

  constructor() Ownable() public {
    setLinkToken(RINKEBY_LINK_ADDRESS);
    setOracle(RINKEBY_ORACLE_ADDRESS);
  }
  
  function requestPrice() public onlyOwner {
    ChainlinkLib.Run memory run = newRun(SPEC_ID, this, "fulfill(bytes32,uint256)");
    run.add("url", "https://api.kraken.com/0/public/Ticker?pair=ETHUSD");
    string[] memory path = new string[](4);
    path[0] = "result";
    path[1] = "XETHZUSD";
    path[2] = "c";
    path[3] = "0";
    run.addStringArray("path", path);
    run.addInt("times", 100);
    chainlinkRequest(run, LINK(1));
  }

  function fulfill(bytes32 _requestId, uint256 _price)
    public checkChainlinkFulfillment(_requestId)
  {
    price = _price;
  }
}
```

So `requestPrice` will instruct Chainlink to get the JSON data at Kraken's API, parse the JSON to get the value stored at the end of the path specified, and here you can also tell it to multiply the value by some amount to preserve accuracy.

**Comment by pelsasser** [comment]
@thodges-gh - great super helpful.

So for us it would probably make sense to have a user pass in a `string[]` (that we formulate using our dApp to help them) with all the needed information.  It sounds like we would then do

```
run.addInt("times", 10**PRICE_DECIMAL_PLACES)
```
which would return the price in the correct integer format for the contract.

I will have to do some research into the gas cost of deploying the chainlinked contract for each MarketContract, or if it will be significant gas savings during deployment to create an `oracleHub` that essentially acts as the intermediary between chainlink oracles and our smart contracts.

We had plans to do something similiar with oraclize.it, to reduce deployment costs, but just haven't had the time to implement it yet.

**Comment by thodges-gh** [comment]
Sounds good on the gas savings. Since the callback for Chainlink can be a different contract, you could do something like the examples below. Just note that I took out the Ownable contract so you'll want to secure your contracts so that only your requesters can make calls to the Chainlinked contract.

Requester:
```solidity
pragma solidity ^0.4.24;

import "github.com/smartcontractkit/chainlink/solidity/contracts/Chainlinked.sol";

contract MarketProtocolRequester is Chainlinked {
  address constant RINKEBY_LINK_ADDRESS = 0x01BE23585060835E02B77ef475b0Cc51aA1e0709;
  address constant RINKEBY_ORACLE_ADDRESS = 0x1b12694E8651389c5BB3C094E8fb7e5609b663E7;
  bytes32 constant SPEC_ID = bytes32("b4eaae96efc041d78458960456872047");

  constructor() public {
    setLinkToken(RINKEBY_LINK_ADDRESS);
    setOracle(RINKEBY_ORACLE_ADDRESS);
  }
  
  function requestPrice() public returns (bytes32) {
    ChainlinkLib.Run memory run = newRun(SPEC_ID, msg.sender, "fulfill(bytes32,uint256)");
    run.add("url", "https://api.kraken.com/0/public/Ticker?pair=ETHUSD");
    string[] memory path = new string[](4);
    path[0] = "result";
    path[1] = "XETHZUSD";
    path[2] = "c";
    path[3] = "0";
    run.addStringArray("path", path);
    run.addInt("times", 100);
    return chainlinkRequest(run, LINK(1));
  }
}
```

Consumer:
```solidity
pragma solidity ^0.4.24;


contract Consumer {
  address constant RINKEBY_ORACLE_ADDRESS = 0x1b12694E8651389c5BB3C094E8fb7e5609b663E7;
  IRequester internal requester;
  mapping(bytes32 => bool) internal unfulfilledRequests;
  uint256 public price;
  
  event RequestFulfilled(bytes32 _requestId, uint256 _price);
  
  constructor(address _requester) public {
    requester = IRequester(_requester);
  }
  
  function request() public {
    bytes32 requestId = requester.requestPrice();
    unfulfilledRequests[requestId] = true;
  }

  function fulfill(bytes32 _requestId, uint256 _price)
    public
    checkChainlinkFulfillment(_requestId)
  {
    emit RequestFulfilled(_requestId, _price);
    price = _price;
  }

  modifier checkChainlinkFulfillment(bytes32 _requestId) {
    require(msg.sender == RINKEBY_ORACLE_ADDRESS && unfulfilledRequests[_requestId]);
    _;
    unfulfilledRequests[_requestId] = false;
  }
}

interface IRequester{
  function requestPrice() external returns (bytes32);
}
```

Using the `unfulfilledRequests` mapping and `checkChainlinkFulfillment` modifier helps ensure that not only the callback comes from the oracle contract address, but it's the correct request ID as well. If you're deploying a lot of consumers that utilize the same requester, I think this approach will work well.

**Comment by pelsasser** [comment]
@thodges-gh - deployed the MarketProtocolConsumer contract to
`0x9109d88ac87ad72fb8e5af903fa92878ca5bf7cb` on rinkeby

and then attempted to call requestPrice() which is [reverting](https://rinkeby.etherscan.io/tx/0xf4e10cbc113fcf5557696790a5492d8dd109b966cbfdf368a4b41f285de7382f).

I checked my balance of LINK and looks like I have plenty for this address, so am a bit confused where the revert is occuring. Gonna keep debugging, but any help is appreciated.

**Comment by pelsasser** [comment]
Some logging that may help when attempting to call requestPrice() 

> 
> Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending? 
> Error: gas required exceeds allowance or always failing transaction at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1724108 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1274130 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:370402 at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:388633) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373232 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:370402 at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373508) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373546 at Ht (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:382915) at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373635) at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1275045) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1274612 at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:388577) at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:388655) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373232 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1274578 at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:388577) at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:388655) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373232 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1274951 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:374042 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:370402 at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373508) at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373430) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:373232 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:374022 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1274833 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1273270 at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1392551)

**Comment by thodges-gh** [comment]
I see the problem. The MarketProtocolConsumer needs a LINK balance, not your wallet. So it should work if you send the contract address 1 LINK first, then call `requestPrice`.

**Comment by pelsasser** [comment]
Right, Thanks!  Attempting now.

**Comment by pelsasser** [comment]
@thodges-gh success! - 

https://rinkeby.etherscan.io/tx/0x3067f88d50a561c587a2d822fc5d5a10ea627b527cce111a9375ca439d3632e5

**Comment by pelsasser** [comment]
@thodges-gh - Okay next challenge ;)

```
  function requestPrice(string _url, string[] _path) public onlyOwner {
    ChainlinkLib.Run memory run = newRun(SPEC_ID, this, "fulfill(bytes32,uint256)");
    run.add("url", _url);
    run.addStringArray("path", _path);
    run.addInt("times", 100);
    chainlinkRequest(run, LINK(1));
  }
```

The above code snippet is the ideal way for a user to be able to create the needed run, however with current version of solidity, `string[]` ,translating to `bytes[][]` and is not supported as an argument.  Sounds like this may change in the future, but for the time being, any thoughts on a workaround to a user being able to pass in the needed `path` to parse the json, that allows for an arbitrary number of `path`s

**Comment by pelsasser** [comment]
@thodges-gh - thanks!

Just to be clear overloaded would look like 
```
requestPrice(string _url, string _path)
requestPrice(string _url, string _path1, _path2)
requestPrice(string _url, string _path1, _path2, _path3)
requestPrice(string _url, string _path1, _path2, _path3, _path4)
```
etc...

**Comment by thodges-gh** [comment]
Exactly, and the full implementation (I already had it written up) would look like:

```solidity
  function requestPrice(string _url, string _path0) public onlyOwner {
    ChainlinkLib.Run memory run = newRun(SPEC_ID, this, "fulfill(bytes32,uint256)");
    run.add("url", _url);
    string[] memory path = new string[](1);
    path[0] = _path0;
    run.addStringArray("path", path);
    run.addInt("times", 100);
    chainlinkRequest(run, LINK(1));
  }
  
  function requestPrice(string _url, string _path0, string _path1) public onlyOwner {
    ChainlinkLib.Run memory run = newRun(SPEC_ID, this, "fulfill(bytes32,uint256)");
    run.add("url", _url);
    string[] memory path = new string[](2);
    path[0] = _path0;
    path[1] = _path1;
    run.addStringArray("path", path);
    run.addInt("times", 100);
    chainlinkRequest(run, LINK(1));
  }
  
  function requestPrice(string _url, string _path0, string _path1, string _path2) public onlyOwner {
    ChainlinkLib.Run memory run = newRun(SPEC_ID, this, "fulfill(bytes32,uint256)");
    run.add("url", _url);
    string[] memory path = new string[](3);
    path[0] = _path0;
    path[1] = _path1;
    path[2] = _path2;
    run.addStringArray("path", path);
    run.addInt("times", 100);
    chainlinkRequest(run, LINK(1));
  }
  
  function requestPrice(string _url, string _path0, string _path1, string _path2, string _path3) public onlyOwner {
    ChainlinkLib.Run memory run = newRun(SPEC_ID, this, "fulfill(bytes32,uint256)");
    run.add("url", _url);
    string[] memory path = new string[](4);
    path[0] = _path0;
    path[1] = _path1;
    path[2] = _path2;
    path[3] = _path3;
    run.addStringArray("path", path);
    run.addInt("times", 100);
    chainlinkRequest(run, LINK(1));
  }
```
etc...

**Comment by pelsasser** [comment]
@thodges-gh - once again, thanks for all your help and responsiveness!

I wanted to share some issues / complexities that I have ran into so far, that I think will help both you guys in knowing what the developer experience on top of Chainlink is like and also probably help me to understand if I am implementing this in a way that is harder than it should be.  Here are the suggestions I have, and feedback on my approach is greatly welcomed as well!


#### Packaging your solidity into a npm package 
 we are currently using npm to manage our dependencies.  As mentioned to you previously the `npm install` directly from your GH repo fails (but it does look like yarn install works).  Either way this would really help us to be able to lock to a version (rather than a commit) and I think make some things a little easier.  We have done this with this our solidity, and so far it has worked well for us.

#### Consider using the open-zeppelin package directly imported from npm rather than putting the classes under version control as dependencies in your solidity code base.
Currently, when trying to compile your solidity with our solidity we run into several issues when a contract like `StandardToken` is defined in your codebase and also the open-zeppelin codebase we are importing.  An example of the errors

> 
> openzeppelin-solidity/contracts/token/ERC20/BasicToken.sol:12:1: The previous declaration is here:
> contract BasicToken is ERC20Basic {
> ^ (Relevant source part starts here and spans across multiple lines).
> 
> ,/home/pelsasser/MARKETProtocol/contracts/chainlink/MarketContractChainLink.sol:22:1: DeclarationError: Identifier already declared.
> import "./src/Chainlinked.sol";
> ^-----------------------------^
> openzeppelin-solidity/contracts/token/ERC20/ERC20.sol:10:1: The previous declaration is here:
> contract ERC20 is ERC20Basic {
> ^ (Relevant source part starts here and spans across multiple lines).
> 
> 

Maybe there is an easier way for me to avoid this, but the only work around I was able to find was to modify your solidity to use the open zeppelin package in order to avoid the conflicts.

#### feature request - accepting strings that can be processed off chain rather than string[] to create the run objects.
This is probably more complex than I understand, but if we would be able to avoid the code [here](https://github.com/MARKETProtocol/MARKETProtocol/blob/1b8ea4781732cce8c1217c56c60df9f28403e2de/contracts/chainlink/MarketContractChainLink.sol#L60) that would be very nice. 


Thanks @thodges-gh, I hope this is helpful for you and look forward to any modifications to how I am thinking about the integration that will aid in these issues.

**Comment by pelsasser** [comment]
@thodges-gh - if you are open to it, I can quickly create a PR for importing the open-zeppelin contracts into ChainLink

**Comment by thodges-gh** [comment]
Thank you @pelsasser! I created a bug in our tracker for npm [here](https://www.pivotaltracker.com/story/show/160352152), and a feature request for the strings to be processed in the node [here](https://www.pivotaltracker.com/story/show/160352011). Ideas that help with pushing any amount of computation off-chain is definitely something that we're always interested in exploring. This seems like a feature that would be used quite often.

If you already have everything ready for importing the openzeppelin-solidity contracts, absolutely feel free to open a PR. If you don't already have that ready, don't worry, I can get that in pretty easily. We actually did use that method before, but at the time, Remix was giving us problems getting the nested imports from the node_modules directory. I think it'd be more important for projects to be able to use their own openzeppelin contracts than for just making it easy to use Remix.

**Comment by pelsasser** [comment]
@thodges-gh - thanks that is awesome!  Will keep pushing this forward!

**Comment by pelsasser** [comment]
@thodges-gh re: the PR for open zeppelin I dont have it ready to go.

**Comment by thodges-gh** [comment]
@pelsasser okay, no problem. I know what we need to do and I can get that taken care of. Thank you!

**Comment by thodges-gh** [comment]
@pelsasser, got a PR up [here](https://github.com/smartcontractkit/chainlink/pull/553) to fix our imports. Feel free to let me know if that won't work for you or if there's any additional improvements I can throw in to make it easier. Thank you again!

**Comment by pelsasser** [comment]
@thodges-gh - initial implementation is here - 

https://github.com/MARKETProtocol/MARKETProtocol/pull/130 - needs alot more polish, testing and thought.

Once you guys push through a few of the changes on your end, I will remove your src as well.

Not sure if you will be able to follow what is happening or not, but would be happy to hop on a call to talk through it sometime

**Comment by thodges-gh** [comment]
@pelsasser Awesome! I'm looking through it now. I got the our [#553](https://github.com/smartcontractkit/chainlink/pull/553) merged this morning, so you should be able to use npm for our contracts already.

**Comment by thodges-gh** [comment]
@pelsasser no problem! It should work by adding the following line to your "dependencies" in package.json:
```
"chainlink": "github:smartcontractkit/chainlink"
```

Adding that should also pull in "linkToken" and "solidity-cborutils" contracts to the node_modules directory.

**Comment by thodges-gh** [comment]
@pelsasser that's weird. The linkToken contracts should have been added to node_modules when you ran `npm install` with chainlink as a dependency. I saw this once on my Chainlinked project, and the work around was to simply run `npm install` again. After that, I deleted node_modules and my package-lock.json file and all dependencies were added successfully on the first try. I'd really like to avoid requiring projects from needing to add the LinkToken dependency as well. Totally open to suggestions to improve that, or maybe this is just weird behaviour from npm?

**Comment by pelsasser** [comment]
@thodges-gh - blew away package-lock.json and node_modules, reinstalled, and got a bit further.

Now stuck at the spot where your contracts are importing open-zeppelin from your source, and we are import from there package, so the contracts are colliding.

> 
> ,linkToken/contracts/LinkToken.sol:15:3: Warning: Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.
>   function LinkToken()
>   ^ (Relevant source part starts here and spans across multiple lines).
> ,/home/pelsasser/MARKETProtocol/contracts/chainlink/OracleHubChainLink.sol:22:1: DeclarationError: Identifier already declared.
> import "./MarketContractChainLink.sol";
> ^-------------------------------------^
> linkToken/contracts/token/BasicToken.sol:12:1: The previous declaration is here:
> contract BasicToken is ERC20Basic {
> ^ (Relevant source part starts here and spans across multiple lines).
> 
> ,/home/pelsasser/MARKETProtocol/contracts/chainlink/OracleHubChainLink.sol:22:1: DeclarationError: Identifier already declared.
> import "./MarketContractChainLink.sol";
> ^-------------------------------------^
> linkToken/contracts/token/ERC20.sol:11:1: The previous declaration is here:
> contract ERC20 is ERC20Basic {
> ^ (Relevant source part starts here and spans across multiple lines).
> 
> ,/home/pelsasser/MARKETProtocol/contracts/chainlink/OracleHubChainLink.sol:22:1: DeclarationError: Identifier already declared.
> import "./MarketContractChainLink.sol";
> ^-------------------------------------^
> linkToken/contracts/token/ERC20Basic.sol:9:1: The previous declaration is here:
> contract ERC20Basic {
> ^ (Relevant source part starts here and spans across multiple lines).
> 
> ,/home/pelsasser/MARKETProtocol/contracts/chainlink/OracleHubChainLink.sol:22:1: DeclarationError: Identifier already declared.
> import "./MarketContractChainLink.sol";
> ^-------------------------------------^
> linkToken/contracts/math/SafeMath.sol:8:1: The previous declaration is here:
> library SafeMath {
> ^ (Relevant source part starts here and spans across multiple lines).
> 
> ,/home/pelsasser/MARKETProtocol/contracts/chainlink/OracleHubChainLink.sol:22:1: DeclarationError: Identifier already declared.
> import "./MarketContractChainLink.sol";
> ^-------------------------------------^
> linkToken/contracts/token/StandardToken.sol:15:1: The previous declaration is here:
> contract StandardToken is ERC20, BasicToken {
> ^ (Relevant source part starts here and spans across multiple lines).
> 

I think the only option here is for you to import from open-zepplein directly, IE
```
import "openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol";
```

so we are then using the same contracts.

**Comment by thodges-gh** [comment]
@pelsasser oh I see, sorry about that! I have a PR up on the LinkToken repo [here](https://github.com/smartcontractkit/LinkToken/pull/2) to fix it.

**Comment by thodges-gh** [comment]
@pelsasser I closed [#2](https://github.com/smartcontractkit/LinkToken/pull/2) in favor of [#3](https://github.com/smartcontractkit/LinkToken/pull/3). We didn't want to risk changing the expected functionality of the token since it's already deployed. This is now merged in so you shouldn't have the contract names collide any more.

**Comment by thodges-gh** [comment]
@pelsasser I have an updated oracle contract and JobIDs that will need to be used for Rinkeby once this (https://github.com/smartcontractkit/chainlink/pull/546) PR is merged in our Chainlink repo. Even then, you won't need to use them until you pull in the latest Chainlinked contract from NPM.

Oracle Contract: 0xd1639233c9604904b4d8b5c8a2927986066d3789
Immediate uint256 response JobID: 4a1b7ec37f1d43d3ae81547e3b190c54
Delayed uint256 response JobID: 250f80dfbce24a61801a87b1cbcc4776

I will follow up once the PR is merged, as well as update our official documentation (https://docs.chain.link/v1.0/docs/getting-started#section-deploying-to-the-blockchain) on the new address and JobIDs.

**Comment by pelsasser** [comment]
@thodges-gh - looks like there are still some issues with importing the package from your github src.

> 
>   function LinkToken()
>   ^ (Relevant source part starts here and spans across multiple lines).
> ,chainlink/solidity/contracts/Oracle.sol:7:9: DeclarationError: Identifier not found or not unique.
>   using SafeMath for uint256;
> 

If you take a look at the contract there is no import for the SafeMath library
```

pragma solidity ^0.4.24;

import "openzeppelin-solidity/contracts/ownership/Ownable.sol";
import "linkToken/contracts/LinkToken.sol";

contract Oracle is Ownable {
  using SafeMath for uint256;
```
The good news is by adding 

`import "openzeppelin-solidity/contracts/math/SafeMath.sol";`

I can compile everything!  So we are very close.

**Comment by thodges-gh** [comment]
@pelsasser Oh, that means we were using the SafeMath contract vendored in from the LinkToken project, which was just renamed. Easy fix, I'll get it up. Thank you!

**Comment by thodges-gh** [comment]
@pelsasser https://github.com/smartcontractkit/chainlink/pull/575 is merged with the updated import line for our oracle contract.

**Comment by pelsasser** [comment]
thanks @thodges-gh - as always, very happy about how responsive you guys are with these fixes / requests!

**Comment by pelsasser** [comment]
@thodges-gh - all set, just pushed a commit which closes out the import issues.

**Comment by pelsasser** [comment]
@thodges-gh - thanks for the updated.  I think we are gonna lock to a commit to avoid breaking changes in our CI / testing environment as you guys continue to work on the solidity.

**Comment by pelsasser** [comment]
@thodges-gh - locked to commit b395d572aa34374461e99327e048405c56a575c3 for the time being 

It would be helpful for us if in your future plans you considered releasing packages with versions and release notes. We can then easily know what new features have been implemented and perhaps more importantly any breaking changes when we upgrade. Probably not as important right now with both of us on rinkeby, but as we progress towards production it would be very nice!

**Comment by pelsasser** [comment]
closing via #130 - initial work completed.
