### ISSUE TITLE
Docker is failing with tests 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#120]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.
### User Story
As a user I would like to be able to run tests in docker and travis ci

### Why Is this Needed?
*Summary*:testing is good

### Description
*Type*: Bug

### Current Behavior

> Running: node --max-old-space-size=4096 ../node_modules/.bin/truffle test --network coverage
> (this can take a few seconds)...
> Could not connect to your Ethereum client. Please check that your Ethereum client:
>     - is running
>     - is accepting RPC connections (i.e., "--rpc" option is used in geth)
>     - is accessible over the network
>     - is properly configured in your Truffle configuration file (truffle.js)

### Expected Behavior
Tests run correctly

### Reproduction
See recent travis builds

**Comment by pelsasser** [comment]
@perfectmak - when you have some time can you take a look at this? We can also try and get @cryptomental to help us out as well, I miss him!

**Comment by perfectmak** [comment]
Sure @pelsasser, I'll take a look at it as soon as possible.

@cryptomental we miss you 😇
