### ISSUE TITLE
[Chainlink] Compare costs of storing oracleQueryRunPath on chain vs recreating on demand

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#127]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user, I always want to spend less gas!

### Why Is this Needed?
*Summary*: After creating the `ChainLinkQuery` struct, we are storing the `string[] oracleQueryRunPath` for later use with on demand queries.  It may be better to just recreate it, rather than storing it, which is expensive.

### Description
*Type*: Feature / comparison of benefits

### Solution
*Summary*: Compare gas costs of `requestOnDemandQuery` when creating `oracleQueryRunPath[]` during that call vs when we store it in our struct to see which is better.

### Definition of Done
- [ ] analysis of gas costs for both approaces
- [ ] suggestion on better approach
- [ ] implementation post review by @MARKETProtocol/core

**Comment by rojosnow** [comment]
Closing.
