### ISSUE TITLE
Add optional time lock to collateral 

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#143]
### User Story
As an exchange implementing MARKET Protocol it would be helpful to ensure collateral that is deposited into the collateral for trading is locked for withdraw longer than the life of a given order.  The user could possibly request for early withdraw of the time-locked collateral, and some elapsed number of blocks could then release the collateral early back to the user.  This delay in withdraw would allow for the exchange to cancel any outstanding orders prior to them becoming unfillable / invalid.

### Why Is this Needed?
*Summary*: Possibly better UX all around if the order book is kept in a more valid state. 

### Description
*Type*: Feature

### Solution
*Summary*: Add timelock to user deposited collateral (that isn't locked for an open position), and ability to request early unlock.

**Comment by rojosnow** [comment]
Issue moved to [MARKETProtocol/smartcontracts #2](https://github.com/MARKETProtocol/smartcontracts/issues/2) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pelsasser** [comment]
closed as no longer relevant with new architecture.
