### ISSUE TITLE
Long and Short Token naming conventions

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#156]
### User Story
As a user and developer of MP, we need to determine how to name the short and long tokens and what symbol to be used for them.

### Why Is this Needed?
*Summary*: This will determine how positions show up in a wallet.

### Description
*Type*: Feature

### Current Behavior
erc20 tokens names are generically called "Long Position Token" with symbol "LONG"

### Expected Behavior
we create better naming mechanism in the future

### Definition of Done
- [ ] determing naming mechanism
- [ ] figure out way to create those names, cannot be easily handed into constructor of MarketContract due to abi encoder not allowing nested arrays string[] (which is actually bytes[][]).
- [ ] add needed tests.

**Comment by perfectmak** [comment]
I believe the naming convention we want to take it should somehow show which underlying asset it is trading against or else there might be confusions when trading the same tokens but in different markets.

**Comment by pelsasser** [comment]
Needs to be addressed before launch of minting platform
