### ISSUE TITLE
[Tests] update TraderHelper.js

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#160]
### User Story
As a user I want a helper class that is updated with out new contract structure.

### Description
*Type*: Feature

### Definition of Done
- [ ] update TraderHelper.js for new contract 
- [ ] remove uneeded trading logic
- [ ] fix all comments / notes

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by perfectmak** [comment]
@pelsasser I believe the TradeHelper is no more useful. We should just delete it.

**Comment by pelsasser** [comment]
yup. closing this issue.
