### ISSUE TITLE
[Security] Attack vectors within minting / redemption

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#168]
### Description
There is a potential attack vector with our current architecture that needs to be explored fully.

Set up for scenario - 
```
MarketContract A -
CollateralToken - Dai 
LongTokenAddres - 0x001
ShortTokenAddres - 0x002
```
```
Spoofed MarketContract B -
CollateralToken - FakeCollateral 
LongTokenAddres - 0x001
ShortTokenAddres - 0x002
```

Theoretically an attacker could call mint using MarketContractB, it would transfer and lock the FakeCollateral erc20 token and mint Long and Short tokens, which could then be redeemed in MarketContractA for real Dai.  

This is currently prevented by the factory deploying contract and whitelisting them.  When a factory deploys the contracts, we know for a fact that the LongTokenAddress and ShortTokenAddress are unique (since they are created at construction time).

As an added layer of security, we should add a field to the positions tokens that ties them back to a specific MarketContract so they cannot be issued with any other market contract address that doesn't match the same collateral token.

**Comment by rojosnow** [comment]
@pelsasser Are there any concepts here that would help, https://github.com/AZTECProtocol/AZTEC?

**Comment by pelsasser** [comment]
@rojosnow pretty sure the solution is resolved, just want to make sure its considered and kicked around a bit.
