### ISSUE TITLE
[Settlement] Create a time delay between contract expiration and settlement of funds. 

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKETProtocol#179]
#### User Story

- As an <audience/user>:  user of MPX
- I want to <action/task>: have trading halted immediately upon the expiration of a contract
- so that <outcome/goal/benefit>: no odd trades are made, and then within X hours the contract settles and I am able to redeem collateral.

#### Type

- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Solution
Separating the halt of trading to the actual settlement allows us to simplify the process and make sure we publish values correctly to deal with any possible disputes 

#### Definition of Done
- [ ] add time delay in solidity codebase
- [ ] add needed tests

**Comment by rojosnow** [comment]
@pelsasser This is the issue created for the timeout between contract expiration and settlement to allow for the settlement process and disputes.

**Comment by pelsasser** [comment]
Completed.
