### ISSUE TITLE
Website updates

### ISSUE THREAD

**Issue by seth-market** [MARKETProtocol/MARKETProtocol#194]
#### User Story

- As an <audience/user>:  user
- I want to <action/task>: delete the white paper
- so that <outcome/goal/benefit>: its no longer public since its outdated. 

#### Type

- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Definition of Done
- [ ] remove all links to the WP on website and docs page.

**Comment by rojosnow** [comment]
Issue moved to [MARKETProtocol/website #293](https://github.com/MARKETProtocol/website/issues/293) via [**ZenHub**](https://www.zenhub.com/)
