### ISSUE TITLE
[bug] Fix stage-kovan minting

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKETProtocol#227]
#### Describe the bug

MPX is using incorrect contracts on stage-kovan. Deploy new contracts.

#### Relevant screenshots

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**

**Comment by pelsasser** [comment]
To be clear, only solution to fix staging is to push a new release of MPX, mpx-api, admin
