### ISSUE TITLE
fail safe implementations for oracles

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#25]
Some possible scenarios that can possibly leave a contract in a bad state.

- Bad data from oracle
- Running out of gas to fund needed oracle queries and callbacks

While any user is able to pay for an on demand query and the associated gas costs for that via

`    function requestEarlySettlement() external payable;`

We need to create some escape hatches in the short term and then think about the longer term dispute resolution when issues arise.

**Comment by cryptomental** [comment]
After dropping pre-funding, option 2) is no longer valid. The only option to end the contract before expiration is at requestEarlySettlement(). 

In case of bad data from Oracle:

* after requestEarlySettlement()
* at expiration time

The latter scenario has known timestamp and it should be possible to query Oracle again with this timestamp to get historic price on which the contract can be correctly settled. A new 'DisputeResolver' contract with `function requestPriceAt() external payable` could be created for that or some other mechanism that would allow to resolve the dispute if the contract is settled with an incorrect price.
For requestEarlySettlement() also a timestamp of the request could be stored to help with the dispute.

**Comment by pelsasser** [comment]
https://blog.ethereum.org/2014/03/28/schellingcoin-a-minimal-trust-universal-data-feed/

I think something like this would prove very useful for arbitration - also looking at projects like Kleros
