### ISSUE TITLE
[spike] Standardized contract naming protocol

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#44]
It may be helpful to attempt and create a standardized naming protocol for contracts similar to how financial futures are named.  This may not be fully all encompassing, and certainly people could opt out, but it would allow for easy search, indexing, etc of contracts.

**Comment by cryptomental** [comment]
@pelsasser I believe you are experts in that field but I had some thought on this.  

I would propose a standardized name that would consist of four fields:

A three letter acronym of the data source, e.g.:

```
BIN - Binance
KRA - Kraken
POL - Poloniex
```

A security Symbol: e.g. 
```
ETHUSD
XBTUSD
LTCUSD
BCHUSD
```

Base Token Symbol, e.g.
```
FUSD
FEUR
FCNY
```

Contract expiration, a UNIX timestamp, e.g. `1522361058`.

The full examples would be:

```
KRA_XBTUSD_FUSD_1522361058
KRA_LTCUSD_FUSD_1522361128
```

Using this approach, the contract names could potentially be automatically generated by dApp by enabling a checkbox "Automatically generate contract name" in contract deployer form.

**Comment by pelsasser** [comment]
I like this idea a lot.  It is pretty in line with the ideas around this that I had previously.  There are always going to be some outliers that fall outside of the "convention" which makes it a bit more challenging, but some standardization is better than none.

One other important piece of the contract would be the `PRICE_CAP` and `PRICE_FLOOR`.  If we look at traditional [options markets](https://en.wikipedia.org/wiki/Option_naming_convention), these get included so may not be a bad idea to add them.  Essentially that would make the name very searchable and indexable.

Any thoughts about incorporating those?  The other point is that the data is always available inside of the contract itself....

**Comment by cryptomental** [comment]
I also thought about after I submitted the proposal. I think it makes sense to add those, too.

**Comment by pelsasser** [comment]
REFERENCEASSETSYMBOL_COLLATERALTOKENSYMBOL_DATAPROVIDER_EXPIRATION_USERTEXT

### Examples

BTC_WETH_BIN_1531911382232_PE

BTC_USDT_BIN_1531911382232_001


### Possible problems

- Is there really a need for the expiration since we already store it in contract in the same format? Every added bit of data costs more gas.
- Do we need anything else?
- Contract names may not be unique.

**Comment by pelsasser** [comment]
There is nothing we can do to force uniqueness really, and I don't think we should to be honest.  At the very end of the day the contract address will be unique, AND it is very unlikely two people create identical contracts expiring at the same second.  

Adding fields that already exist in the contract meta data elsewhere (like `FLOOR` and `CAP`) to me seems redundant.  Off chain applications can always grab this data and append the name however they prefer.  I think the only exception to this in my mind is the `EXPIRATION` and I think that is mainly by convention that it seems it should be included as the part of the name.

**Comment by pelsasser** [comment]
closing in deference to epic https://github.com/MARKETProtocol/dApp/issues/268
