### ISSUE TITLE
Dynamic Query Costs when using Oraclize.it

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#48]
Currently, we have some hard coded [variables](https://github.com/MarketProject/MarketProtocol/blob/f6d83764e3e60ac2f6468de2e373d566f9dbac2b/contracts/oraclize/MarketContractOraclize.sol#L34) in order to ensure sufficient funding by the contract creator for the required numbers of queries they have created in the contract.  This is less than ideal because

- Wolfram Alpha Queries cost 3x URL queries
- As the price of ETH changes, these are no longer valid and [Oraclize.it](http://docs.oraclize.it/#pricing) roughly pegs cost to USD

One of the challenges to creating a better solution is the Oraclize.it API does allow you to query the expected price, but the first query is free, so at contract creation, their API reports no cost (since the next query is free) but the subsequent queries price isn't available.   While we can correct for this in the contract deployment dApp - it would be nice to be able to find a solution that correctly handles this in the protocol layer itself rather than hard coding values, that are already currently very outdated.

**Comment by pelsasser** [comment]
Another thought - perhaps this doesn't really need to be in the protocol / on chain at all.  The dApp for deployment can enforce the requirements in a nicer way.

**Comment by cryptomental** [comment]
If I understood correctly, this should be possible with QueryHub contract.

**Comment by rojosnow** [comment]
Closing.
