### ISSUE TITLE
Allow for dynamic setting of Oraclize gas prices for callback

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#52]
Currently, these are set at 20 gwei which is the default from Oraclize.it - in times of network stress we may need to allow the contract creator to increase these in order for the contract to be forced in to settlement.

This needs to be thought about carefully, as it is possible a contract creator will not care to push the contract into settlement.  Potentially the MKT token contract could be the one to do this. 

more thought on this is needed.

**Comment by maektwain** [comment]
Would like to work on this issue. @pelsasser I can research a little bit about dynamic fee setting.

**Comment by pelsasser** [comment]
@maektwain - with the current implementation this may actually not be possible.  It will be dependent upon oraclize.it 

Some background - 

Oraclize.it currently set the default gas price for the callback from them at 20 gwei.  This is typically a very high amount and the transactions get processed very quickly. However in times of network congestion this could mean that a callback to settle the contract is delayed.  This isn't a massive problem, since the payload for that transaction (the settlement price) isn't what is delayed, just the processing of that settlement price.

Oraclize.it may not offer the functionality to change the needed call back gas after a query has been created since that wold effect the cost of the query itself.  

Happy to have you research it, but it may be a dead end for the time being, and it may also not be that big of an issue when we consider what is actually being delayed in a congested network state.

**Comment by rojosnow** [comment]
Closing.
