### ISSUE TITLE
[Oraclize] Add require statements for all Oraclize Queries

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#67]
The Oraclize API has a sanity check around the price of the query that can be seen [here](https://github.com/MARKETProtocol/MARKETProtocol/blob/b9278d78a20a2e35e7a41b8ebd5e4a45bfd25e7d/contracts/oraclize/oraclizeAPI.sol#L140) 

We should create error handling in the needed locations where queries are being scheduled.  Most likely a simply require(queryID != 0) should suffice.

**Comment by garyaka** [comment]
I am thinking that you may not want to change oraclizeAPI.sol file.
but have require (and you already have some ) statements in files where you are using them.
This is partially to be able to update oracliApi easily in the future.
