### ISSUE TITLE
[Tests] standardize code style across all JavaScript tests.

### ISSUE THREAD

**Issue by 0xean** [MARKETProtocol/MARKETProtocol#71]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently we have some differing styles amount many of the .js test files and utilities for testing.  We should bring these in line with the standards of our other projects styles for readability and consistency. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Some of the .js files are using 2 spaces, other's tabs 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Consistency!

### Solution

Reformat all non solidity code to match `dApp` style (could possibly be talked into reformatting the solidity as well, certainly open to discussion)

**Comment by arun1595** [comment]
@pelsasser I would like to fix this :smile:

**Comment by pelsasser** [comment]
@arun1595 that would be incredible! thanks!  If you are gonna tackle it let me know, and I will mark it as such.  If we can create linting for the javascript sections of code that would be really helpful as well.

**Comment by pelsasser** [comment]
All yours ;)

**Comment by arun1595** [comment]
@pelsasser As I am working on https://github.com/MARKETProtocol/dApp/issues/153, can you please remove the 'In Progress' label?

**Comment by I3uckwheat** [comment]
I would like to work on this! Seems fun!

**Comment by eswarasai** [comment]
@I3uckwheat -- Sure. Please do post a plan of action here before starting to work on it, so that we can suggest any changes, if at all any. Thanks for your interest in MARKET Protocol and helping us out here. Feel free to join our [Discord](https://marketprotocol.io/discord) channel in case you have any questions.

**Comment by I3uckwheat** [comment]
@eswarasai I am new to this project, and also new to joining into existing projects. Thanks for having me!

My plan of action is as follows:

- Run prettier to change all 4 space indentation to 2 space indentation
- Change any `require`s into `import` statements (as dApp seems to have)
- verify double quotes are changed to single quotes when possible
- setup eslint in compliance of the npm style guide (as noted in the contributing section of the readme)


Does this seem adequate?

**Comment by eswarasai** [comment]
@I3uckwheat -- Sounds good to me. How about using [`prettier-eslint`](https://github.com/prettier/prettier-eslint)? Any thoughts on this?

PS: I've just realized that `.eslintrc` of `dApp` isn't up-to-date with the `prettier` setup we have configured. I might actually update the `dApp` to also use `prettier-eslint` once you give a go-ahead on this.

**Comment by I3uckwheat** [comment]
I like the idea of it: however, I believe we should still maintain separate .prettierrc and .eslintrc.json files so people can use their in-editor linters if they'd like. I believe that package can import a filename for the configuration as well.

**Comment by I3uckwheat** [comment]
@eswarasai I opted to use `prettier-eslint-cli` instead, as it integrates easily with npm run
