### ISSUE TITLE
Update oraclizeApi to 0.5 version which supports solidity 0.4.18

### ISSUE THREAD

**Issue by garyaka** [MARKETProtocol/MARKETProtocol#73]
### Why Is this Needed?
*Summary*:
Use more current version of the code to have functions have less errors.

*Type*:  Feature

### Solution
*Summary*: Update `oraclizeApi` to `0.5` version which supports solidity `0.4.18`

 Definition of Done
Replace current `oraclizeAPI` with the newer version. Test that none of the current code breaks and if it does, please do fix them.

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

**Comment by cryptomental** [comment]
I will have a look at this.

**Comment by cryptomental** [comment]
@pelsasser I am wondering which change caused test failures on coverage network - I will now cherry-pick  one by one and find the culprit.

**Comment by pelsasser** [comment]
@cryptomental - thanks for all your hard work!

**Comment by cryptomental** [comment]
@pelsasser I also added a complete compiler warnings rework to this pull request.

**Comment by pelsasser** [comment]
closing! thanks @cryptomental
