### ISSUE TITLE
Refactor `baseTokenAddress` to `collateralTokenAddress`

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#98]
### User Story

 As a user, I find the `baseTokenAddress` or `baseToken` to be more confusing than just calling it the `collateralToken` or `collateralTokenAddress` 

### Why Is this Needed?

*Summary*: to discuss if we should refactor this now!

### Description

*Type*: Discussion

### Current Behavior
`baseToken` used

### Expected Behavior
`collateralToken` used

### Solution

*Summary*: refactor all code and docs and eventually upstream applications as well

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
cc @eswarasai @perfectmak @cryptomental @rojosnow would love any input here.

**Comment by eswarasai** [comment]
@pelsasser -- Do we use `baseToken` somewhere already? I don't remember having this in `dApp` anywhere. I'd say now is the best time to refactor without breaking much of the changes in case we'd want to.

**Comment by cryptomental** [comment]
To be honest when I started with MARKET I was also confused with the baseToken vs collateralToken. +1 for the refactoring.

**Comment by pelsasser** [comment]
okay, I think I am going to go ahead with this then.

**Comment by pelsasser** [comment]
closed in #101
